### PR TITLE
Implementation of TimeTree deletion logic

### PR DESCRIPTION
**Pull request by nsinha123**
Creating a TimeTree node is working fine, but deleting is giving problem. For example when a timetree node is to be created, the CHILD, FIRST, LAST and NEXT associations automatically get created between the associated nodes. If a new node comes in-between two nodes, then the two adjacent nodes adjust their NEXT relations and the timetree becomes perfect. But when a timetree node is deleted, the adjacent nodes don’t adjust their NEXT relations and hence the timetree traversal is broken! We can fix this by simply taking the previous node’s NEXT relation and pointing it into next node. But suppose if we want to delete the timetree nodes for a year and the resolution is second, then all these adjustment of second nodes’ NEXT relations is wastage of time, since it’s most likely that the adjacent second node will also be deleted. If we need to delete a particular node at random, then we can take the NEXT pointer from the left node and point it to the right node, but when millions of adjacent nodes will be deleted at once, then we need to apply some different logic.
I have applied some logic on my own for greater efficiency and faster performance. I am thinking of presenting this code so that you can think of collaborating it in the future.

### CODE REVIEW

**Comment by nsinha123** [comment]
package com.timetree.helper;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import org.neo4j.graphdb.Direction;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Label;
import org.neo4j.graphdb.Node;
import org.neo4j.graphdb.Relationship;
import org.neo4j.graphdb.RelationshipType;
import org.neo4j.graphdb.factory.GraphDatabaseFactory;

import com.graphaware.module.timetree.SingleTimeTree;
import com.graphaware.module.timetree.TimeTreeBackedEvents;
import com.graphaware.module.timetree.api.TimeInstantVO;
import com.graphaware.module.timetree.domain.TimeInstant;
import com.graphaware.module.timetree.logic.TimeTreeBusinessLogic;
import com.graphaware.module.timetree.logic.TimedEventsBusinessLogic;

public class TimeTreeDeleteClass {
	
	public static GraphDatabaseService db;
	public static SingleTimeTree st;
	public static TimeTreeBackedEvents ttbe;
	public static TimeTreeBusinessLogic ttbl;
	public static TimedEventsBusinessLogic tebl;	

	public static String res;
	public static String timeZone;
	public static Properties prop;

	public TimeTreeDeleteClass() {
		init();
	}

	private static void init() {
		try{
			db =  new GraphDatabaseFactory( ).newEmbeddedDatabase( new File("C:/neo4j-enterprise-3.0.6/data/databases/graph.db") );
			st = new SingleTimeTree(db);
			ttbl = new TimeTreeBusinessLogic(db);
			ttbe = new TimeTreeBackedEvents(st);
			tebl = new TimedEventsBusinessLogic(db, ttbe);
		}catch(Exception e )
		{
			e.printStackTrace();
		}
	}

	//This method will delete all the timetree nodes present within the argument
	//It will adjust the CHILD, FIRST, LAST and NEXT relations appropriately so that even after deletion
	//of certain node(s), the traversal within the timetree is not broken
	private void deleteNodeList(List<Node> timeTreeNodes) {
		List<Node> parentsToBeProcessed = new ArrayList<Node>();

		for (Node nodeTobeDeleted : timeTreeNodes) {
			//At first find out the parents and save them in a list
			Iterable<Relationship> parentRelations = nodeTobeDeleted.getRelationships(Direction.INCOMING, RelationshipType.withName("CHILD"));
			for(Relationship parentRelation : parentRelations) {
				Node parent = parentRelation.getOtherNode(nodeTobeDeleted);
				if (!parentsToBeProcessed.contains(parent))
					parentsToBeProcessed.add(parent);
			}
		}

		//Now delete the nodes
		for (Node nodeTobeDeleted : timeTreeNodes) {
			//If resolution is not the leaf of the timetree (for example resoluion is minute or hour) then we need to delete the children
			Iterable<Relationship> childRelations = nodeTobeDeleted.getRelationships(Direction.OUTGOING, RelationshipType.withName("CHILD"));
			if (childRelations!=null && childRelations.iterator().hasNext()) {
				List<Node> childrenToBeDeleted=new ArrayList<Node>();
				for(Relationship childRelation : childRelations){
					Node child = childRelation.getOtherNode(nodeTobeDeleted);
					childrenToBeDeleted.add(child);
				}
				deleteChildren(childrenToBeDeleted);
			}
			//If the label is TimeTreeRoot, then don't delete the node. 
			//We need to keep the TimeTreeRoot forever
			//Loop through all the labels and if one such label is TimeTreeRoot, then set a flag
			boolean flag = false;
			Iterable<Label> labels = nodeTobeDeleted.getLabels();
			for(Label label : labels) {
				if (label.toString().equalsIgnoreCase("TimeTreeRoot")) {
					flag = true;
					break;
				}
			}
			if (flag == false)
				deleteNode(nodeTobeDeleted);
		}
		
		//We need to create this list for the next processing where we need to adjust the NEXT node between children of adjacent parents
		List<Node> parentsToBeProcessedLater = new ArrayList<Node>(parentsToBeProcessed);
		Node first=null;
		Node last=null;
		
		//Now revisit the parents
		for (Node parent: parentsToBeProcessed) {
			Map<Node,String> childrenList =new HashMap<Node,String>();

			//Find out all the children of this parent
			//Also save all the children in a map and check whether FIRST and/or LAST is present
			Iterable<Relationship> childRelations = parent.getRelationships(Direction.OUTGOING, RelationshipType.withName("CHILD"));
			Iterable<Relationship> firstRelations = parent.getRelationships(Direction.OUTGOING, RelationshipType.withName("FIRST"));
			Iterable<Relationship> lastRelations = parent.getRelationships(Direction.OUTGOING, RelationshipType.withName("LAST"));
			int count = 0;
			for(Relationship childRelation : childRelations){
				Node child = childRelation.getOtherNode(parent);
				childrenList.put(child, "");
				//Find out the relationship with this child, whether FIRST or LAST is present
				//But if it is called from deleteSingleNode(), then child may have both FIRST and LAST
				for(Relationship firstRelation : firstRelations){
					if (firstRelation.getOtherNode(parent).equals(child))
						first = child;
				}
				for(Relationship lastRelation : lastRelations){
					if (lastRelation.getOtherNode(parent).equals(child))
						last = child;
				}
				count++;
			}

			if (count == 0) {
				//So no more child is existing under this parent, so we can delete this node
				//But we need to again process it's parent and hence call the deleteNodeList()
				//Also delete this parent entry from the parentsToBeProcessed list
				//Then we will be able to iterate over the parentsToBeProcessed list in the next loop
				List<Node> parentToBeDeleted = new ArrayList<Node>();
				parentToBeDeleted.add(parent);
				parentsToBeProcessedLater.remove(parent);
				deleteNodeList(parentToBeDeleted);
			}

			else if (count == 1) {
				//The child should have all the relationships, FIRST, CHILD and LAST with the parent 
				//So if one relationship is not present, add it
				Node child = childRelations.iterator().next().getOtherNode(parent);
				Iterable<Relationship> relations = child.getRelationships(Direction.INCOMING);

				for(Relationship relation : relations){
					if (relation.getType().equals(RelationshipType.withName("FIRST"))) {
						//So FIRST relationship is already present, so add LAST
						parent.createRelationshipTo(child, RelationshipType.withName("LAST"));
					}
					if (relation.getType().equals(RelationshipType.withName("LAST"))) {
						//So LAST relationship is already present, so add FIRST
						parent.createRelationshipTo(child, RelationshipType.withName("FIRST"));
					}
				}
			}

			else {
				//Two or more number of nodes
				//Check the first and last nodes connected by NEXT relationship
				//But nodes of adjacent parents are also connected by NEXT
				//So we need to check for NEXT relationship only within the siblings
				//One end should have FIRST and the other end should have LAST
				//Done!!!

				if (first!=null && last!=null) {
					//We are processing this parent since it's children were deleted, but both FIRST and LAST nodes are present
					//Hence this case will only appear when in-between nodes were deleted
					//Connect the nodes by NEXT relation while traversing from FIRST to LAST
					while (first.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
						first = first.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(first);
					}
					//So after the above block, first node doesn't have the OUTGOING NEXT relation

					while (last.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
						last = last.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(last);
					}
					//So after the above block, last node doesn't have the INCOMING NEXT relation

					//Join first and last
					first.createRelationshipTo(last, RelationshipType.withName("NEXT"));

				}
				else if (first!=null) {
					//Check the last node from the children by iterating through the NEXT links
					//While iterating we need to always check whether the node is a child of the parent
					Iterable<Relationship> relations = first.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT"));
					Node next = relations.iterator().next().getOtherNode(first); 
					while (childrenList.containsKey(next) && next.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT"))!=null && next.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
						next = next.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(next);
					}
					last=next;
					parent.createRelationshipTo(last, RelationshipType.withName("LAST"));
				}
				else if (last!=null) {
					//Check the first node from the children by iterating through the NEXT links
					//While iterating we need to always check whether the node is a child of the parent
					Iterable<Relationship> relations = last.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT"));
					Node previous = relations.iterator().next().getOtherNode(last);
					while (childrenList.containsKey(previous) && previous.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT"))!=null && previous.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
						previous = previous.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(previous);
					}
					first=previous;
					parent.createRelationshipTo(first, RelationshipType.withName("FIRST"));
				}
			}
		}

		for (Node parent: parentsToBeProcessedLater) {
			//Connect the LAST child of this parent to the FIRST child of the next parent
			//Do this for each parent and we are done!
			//This case will arise when intermediate nodes are deleted from the timetree
			//We need to do this in a separate loop since we want that all the nodes should already be deleted and 
			//FIRST & LAST relationship should already be setup under each parent
			//You may think that the parent node may not have the OUTGOING NEXT - that's not an issue
			//In that case that parent will be omitted and whichever parent has the OUTGOING NEXT that parent's LAST
			//node will be linked to the adjacent parent's FIRST node
			if (parent.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
				Node adjacentParent = parent.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(parent);
				//Find out adjacentParent's FIRST node
				Iterable<Relationship> relations = adjacentParent.getRelationships(RelationshipType.withName("FIRST"));
				Node adjacentFirst = relations.iterator().next().getOtherNode(adjacentParent);
				if (last.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT"))==null && !last.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
					last.createRelationshipTo(adjacentFirst, RelationshipType.withName("NEXT"));
				}
			}
		}
	}

	private void deleteChildren(List<Node> childrenToBeDeleted) {
		for (Node child : childrenToBeDeleted) {
			Iterable<Relationship> grandChildRelations = child.getRelationships(Direction.OUTGOING, RelationshipType.withName("CHILD"));
			if (grandChildRelations!=null && grandChildRelations.iterator().hasNext()) {
				List<Node> grandChildrenToBeDeleted=new ArrayList<Node>();
				for(Relationship grandChildRelation : grandChildRelations){
					Node grandChild = grandChildRelation.getOtherNode(child);
					grandChildrenToBeDeleted.add(grandChild);
				}
				deleteChildren(grandChildrenToBeDeleted);
			}
			deleteNode(child);
		}
	}

	private void deleteNode(Node node) {
		Iterable<Relationship> allRelationships = node.getRelationships();
		for (Relationship relationship : allRelationships) {
			relationship.delete();
		}
		node.delete();
	}
	
	public List<Node> getTimeTreeNodes(long startTime, long endTime, String res, String timezone) {
		List<Node> insNodes = new ArrayList<Node>();
		if(endTime==0L){
			Node insNode = ttbl.getInstant(startTime, res, timezone);
			insNodes.add(insNode);
		}else{
			//insNodes = ttbl.getInstants(startTime, endTime, res, timezone);
			TimeInstant startTimeInstant = TimeInstant.fromValueObject(new TimeInstantVO(startTime, res, timezone));
			TimeInstant endTimeInstant = TimeInstant.fromValueObject(new TimeInstantVO(endTime, res, timezone));
			Node startNode = st.getInstantAtOrAfter(startTimeInstant);
			Node endNode = st.getInstantAtOrBefore(endTimeInstant);
			insNodes.add(startNode);
			while (startNode.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().hasNext()) {
				startNode = startNode.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT")).iterator().next().getOtherNode(startNode);
				insNodes.add(startNode);
				if (startNode.getId()==endNode.getId())
					break;
			}
		}
		return insNodes;
	}
	
	//This method is for deleting a single node at random, not for deleting a list of nodes at once
	//In this case at first nodeTobeDeleted will create a NEXT relationship between it's previous node and it's next node 
	//If nodeTobeDeleted has a FIRST relationship, then it will create a FIRST relationship between it's parent and the next node (provided the next node is its sibling)
	//If nodeTobeDeleted has a LAST relationship, then it will create a LAST relationship between it's parent and the previous node (provided the previous node is its sibling)
	//Then nodeTobeDeleted will be deleted
	//Then this method will be called for those parents who has no child
	//This way this method will be called with each parent list
	//So we need to return the parent node
	private Node deleteSingleNode (Node nodeTobeDeleted) {
		Iterable<Relationship> parentRelations = nodeTobeDeleted.getRelationships(Direction.INCOMING, RelationshipType.withName("CHILD"));
		Node parent = null;
		Node previous = null;
		Node next = null;
		for(Relationship parentRelation : parentRelations) {
			parent = parentRelation.getOtherNode(nodeTobeDeleted);
		}
		
		Iterable<Relationship> incomingNextRelations = nodeTobeDeleted.getRelationships(Direction.INCOMING, RelationshipType.withName("NEXT"));
		previous = incomingNextRelations.iterator().next().getOtherNode(nodeTobeDeleted);
		
		Iterable<Relationship> outgoingNextRelations = nodeTobeDeleted.getRelationships(Direction.OUTGOING, RelationshipType.withName("NEXT"));
		next = outgoingNextRelations.iterator().next().getOtherNode(nodeTobeDeleted);
		
		previous.createRelationshipTo(next, RelationshipType.withName("NEXT"));
		
		Iterable<Relationship> firstRelations = nodeTobeDeleted.getRelationships(Direction.INCOMING, RelationshipType.withName("FIRST"));
		if (firstRelations.iterator().hasNext()) {
			//Check next node's parent
			Iterable<Relationship> nextParentRelations = next.getRelationships(Direction.INCOMING, RelationshipType.withName("CHILD"));
			for(Relationship nextParentRelation : nextParentRelations) {
				Node nextParent = nextParentRelation.getOtherNode(next);
				if (parent.getId()==nextParent.getId()) {
					//If next node doesn't have the FIRST RelationshipType, then create it
					Iterable<Relationship> nextFirstRelations = next.getRelationships(Direction.INCOMING, RelationshipType.withName("FIRST"));
					if (!nextFirstRelations.iterator().hasNext()) {
						parent.createRelationshipTo(next, RelationshipType.withName("FIRST"));
					}
				}
			}
		}
		
		Iterable<Relationship> lastRelations = nodeTobeDeleted.getRelationships(Direction.INCOMING, RelationshipType.withName("LAST"));
		if (lastRelations.iterator().hasNext()) {
			//Check previous node's parent
			Iterable<Relationship> previousParentRelations = previous.getRelationships(Direction.INCOMING, RelationshipType.withName("CHILD"));
			for(Relationship previousParentRelation : previousParentRelations) {
				Node previousParent = previousParentRelation.getOtherNode(previous);
				if (parent.getId()==previousParent.getId()) {
					//If previous node doesn't have the LAST RelationshipType, then create it
					Iterable<Relationship> previousLastRelations = previous.getRelationships(Direction.INCOMING, RelationshipType.withName("LAST"));
					if (!previousLastRelations.iterator().hasNext()) {
						parent.createRelationshipTo(previous, RelationshipType.withName("LAST"));
					}
				}
			}
		}
		
		//Now delete the node
		deleteNode(nodeTobeDeleted);
		
		return parent;
	}
	
	public static void main(String args[]) {
		Long startTime = 1451606400000L;
		Long endTime = 1483228800000L;
		String res = "Second";
		String timeZone = "UTC";
		TimeTreeDeleteClass obj = new TimeTreeDeleteClass(); 
		List<Node> timeTreeNodes = obj.getTimeTreeNodes(startTime, endTime, res, timeZone);
		//Call deleteNodeList() method to delete all the timetree nodes lying within that timeRange
		obj.deleteNodeList(timeTreeNodes);
		//Call deleteSingleNode() to delete a particular timetree node
		//obj.deleteSingleNode(nodeTobeDeleted);
	}
}

**Comment by ikwattro** [comment]
@nsinha123 why did you closed the PR ?

**Comment by nsinha123** [comment]
Hi @ikwattro : sorry! This is the first time I am working in github! I thought Close means Submit. Please inform me what to do right now? Thanks.

**Comment by ikwattro** [comment]
Hi @nsinha123 you can just re-open it. However it seems that you select the target branch to be `ikwattro-patch-1` where it should be `master`

**Comment by nsinha123** [comment]
Hi @ikwattro : thanks a ton for the correction.

**Pull request merged**
